# Generated by Django 5.2 on 2025-06-17 06:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(help_text='A unique slug for the post URL.', max_length=250, unique_for_date='publish_date')),
                ('content', models.TextField(help_text='The main content of the blog post, written in Markdown or HTML.')),
                ('thumbnail', models.ImageField(blank=True, help_text='The main image for the post.', null=True, upload_to='blog_thumbnails/')),
                ('meta_description', models.TextField(blank=True, help_text='A short summary for SEO (150-160 characters).', max_length=160, null=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('SC', 'Scheduled'), ('PB', 'Published')], default='DF', max_length=2)),
                ('is_active', models.BooleanField(default=True, help_text='Controls if the post is visible on the site. Inactive posts are hidden.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the post will be or was published.')),
                ('appreciations', models.ManyToManyField(blank=True, related_name='appreciated_posts', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='admin_app.tag')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned comments appear at the top of the comment section.')),
                ('author', models.ForeignKey(help_text='The user who wrote the comment.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='admin_app.post')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='admin_app_c_created_325ccd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publish_date'], name='admin_app_p_publish_688464_idx'),
        ),
    ]
