# Generated by Django 5.2 on 2025-06-18 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_post_is_recommended_alter_post_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.RemoveField(
            model_name='post',
            name='appreciations',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
